/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Articles: typeof import('./src/components/Articles.vue')['default']
    copy: typeof import('./src/components/Packages copy.vue')['default']
    'IconCarbon:logoGithub': typeof import('~icons/carbon/logo-github')['default']
    'IconCarbon:logoNpm': typeof import('~icons/carbon/logo-npm')['default']
    'IconCarbon:moon': typeof import('~icons/carbon/moon')['default']
    'IconCarbon:sun': typeof import('~icons/carbon/sun')['default']
    'IconGg:npm': typeof import('~icons/gg/npm')['default']
    'IconIc:roundEmail': typeof import('~icons/ic/round-email')['default']
    'IconIconoir:npm': typeof import('~icons/iconoir/npm')['default']
    'IconIon:logoNpm': typeof import('~icons/ion/logo-npm')['default']
    'IconIon:octicon:repo24': typeof import('~icons/ion/octicon-repo24')['default']
    'IconMaterialSymbols:locationOn': typeof import('~icons/material-symbols/location-on')['default']
    'IconOcticon:logoNpm': typeof import('~icons/octicon/logo-npm')['default']
    'IconOcticon:npm': typeof import('~icons/octicon/npm')['default']
    'IconOcticon:repo': typeof import('~icons/octicon/repo')['default']
    'IconOcticon:repo16': typeof import('~icons/octicon/repo16')['default']
    'IconOcticon:repo24': typeof import('~icons/octicon/repo24')['default']
    'IconTabler:brandNpm': typeof import('~icons/tabler/brand-npm')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Packages: typeof import('./src/components/Packages.vue')['default']
    Plum: typeof import('./src/components/Plum.vue')['default']
    Profile: typeof import('./src/components/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
  }
}
