/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IconCarbon:logoGithub': typeof import('~icons/carbon/logo-github')['default']
    'IconCarbon:moon': typeof import('~icons/carbon/moon')['default']
    'IconCarbon:sun': typeof import('~icons/carbon/sun')['default']
    'IconIc:roundEmail': typeof import('~icons/ic/round-email')['default']
    'IconMaterialSymbols:locationOn': typeof import('~icons/material-symbols/location-on')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Plum: typeof import('./src/components/Plum.vue')['default']
    Profile: typeof import('./src/components/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
  }
}
